# Generated by Django 4.2.6 on 2023-10-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'платеж', 'verbose_name_plural': 'платежи'},
        ),
    ]
