# Generated by Django 4.2.6 on 2023-10-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_alter_payment_paid_course_alter_payment_paid_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('name',), 'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
    ]
