# Generated by Django 4.2.5 on 2023-10-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='link',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
