# Generated by Django 4.2.5 on 2023-10-31 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_course_cost_lesson_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid_cost',
        ),
    ]
