# Generated by Django 4.2.5 on 2023-10-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0014_remove_payment_paid_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='cost',
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_cost',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
