# Generated by Django 4.2.5 on 2023-11-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0015_remove_lesson_cost_payment_paid_cost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
